name: "Moonlight Web"
description: "A local moonlight web stream addon"
version: "0.0.5"
slug: "moonlight-web-stream_addon"
init: false
#host_network: true
arch:
  - aarch64
  - amd64
panel_admin: false
panel_icon: mdi:lan
ingress: true
ingress_port: 8080
